site_name: Medicalai
site_description: 'Medicalai'
site_url: https://aibharata.github.io/medicalAI/
site_description: Medicalai framework - high performance, easy to learn, fast to code,
  ready for production
site_author: 'Vinayaka Jyothi For AiBharata'
docs_dir: docs/
repo_name: 'aibharata/medicalAI'
repo_url: 'https://github.com/aibharata/medicalAI'
nav:
    - Home: index.md
    - Data Processing Pipeline: medicalai/dataset_processors.md
    - Core: medicalai/core.md
    - AI Networks: medicalai/networks.md
    - Model Statistics: medicalai/modelStats.md
theme:
  name: 'material'
  favicon: img/logo.png
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  logo: img/logo.png

plugins:
  - search
  - awesome-pages
