site_name: Medicalai
site_description: 'Medicalai'
site_author: 'AiBharata'
docs_dir: docs/
repo_name: 'aibharata/medicalAI'
repo_url: 'https://github.com/aibharata/medicalAI'
nav:
    - Home: index.md
    - Data Processing Pipeline: medicalai/dataset_processors.md
    - Core: medicalai/core.md
    - AI Networks: medicalai/networks.md
    - Model Statistics: medicalai/modelStats.md
theme:
  name: 'material'