site_name: Medicalai
site_description: 'Medicalai'
site_url: https://aibharata.github.io/medicalAI/
site_description: Medicalai framework - high performance, easy to learn, fast to code,
  ready for production
site_author: 'Vinayaka Jyothi For AiBharata'
docs_dir: docs/
repo_name: 'aibharata/medicalAI'
repo_url: 'https://github.com/aibharata/medicalAI'
nav:
    - Home: index.md
    - Example: medicalai/Examples.md
    - Data Processing Pipeline: medicalai/dataset_processors.md
    - Core: medicalai/core.md
    - AI Networks: medicalai/networks.md
    - Model Statistics: medicalai/modelStats.md
theme:
  name: 'material'
  favicon: img/logo.png
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  logo: img/logo.png

plugins:
  - search
  - awesome-pages

edit_uri: ''

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - https://sidecar.gitter.im/dist/sidecar.v1.js
  - js/termynal.js
  - js/custom.js
  - js/chat.js


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - markdown_include.include:
      base_path: docs
  - admonition
  - extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
      - class: mermaid
        format: !!python/name:pymdownx.superfences.fence_div_format ''
        name: mermaid
      - class: arithmatex
        format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        name: math
  - pymdownx.highlight:
      extend_pygments_lang:
      - lang: php
        name: php-inline
        options:
          startinline: true
      - lang: pycon
        name: pycon3
        options:
          python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
      - class: arithmatex
        format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
        name: math
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
